name: Automated Daily Commit

on:
  schedule:
    - cron: '30 2 * * *'  # This runs daily at 02:30 UTC. Adjust the time if needed.
  workflow_dispatch:     # This allows you to run the workflow manually for testing.

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # This ensures the GITHUB_TOKEN is kept for push operations

      - name: Append daily update and commit changes (23f3004212@ds.study.iitm.ac.in)
        run: |
          # Append a timestamp to daily-log.txt (create the file if it doesn't exist)
          echo "Daily update: $(date)" >> daily-log.txt
          
          # Configure git with a name and email for the commit
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "23f3004212@ds.study.iitm.ac.in"
          
          # Stage the changes
          git add daily-log.txt
          
          # Check if there are any changes staged
          if ! git diff --cached --quiet; then
            git commit -m "Automated daily update: $(date)"
            git push
          else
            echo "No changes to commit."
          fi

