
name: Automated Daily Commit

on:
  schedule:
    - cron: '30 2 * * *'  # Runs daily at 02:30 UTC (change if needed)
  workflow_dispatch:  # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Add Daily Commit (23f3004212@ds.study.iitm.ac.in)
        run: |
          echo "Daily update: $(date)" >> daily-log.txt
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "23f3004212@ds.study.iitm.ac.in"
          git add daily-log.txt
          git commit -m "Automated daily update: $(date)"
          git push
